# Generated by Django 4.2.7 on 2023-12-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                ("idcareer", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("shortname", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="myapp/careers/")),
                ("state", models.CharField(max_length=1)),
            ],
        ),
    ]
